"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Bar = { time: number; open: number; high: number; low: number; close: number; volume: number };
type Drawing = { type: "trend" | "horizontal" | "rect"; x1: number; y1: number; x2: number; y2: number };
type Tool = "cursor" | "trend" | "horizontal" | "rect" | "erase";
type ExitPlan = { stopLoss: number; takeProfit: number; exitMinute: number };
type Position = { strike: number; qty: number; entry: number; openedMinute: number } & ExitPlan;
type TradeEvent = { id: number; minute: number; kind: "analysis" | "risk" | "trade" | "discipline"; text: string };
type PendingOrder = { id: number; strategy: "call" | "spread"; strike: number; shortStrike?: number; qty: number; limit: number; placedMinute: number } & ExitPlan;
type SpreadPosition = { longStrike: number; shortStrike: number; qty: number; entryDebit: number; openedMinute: number } & ExitPlan;
type TrainingRecord = { id:number; score:number; pnl:number; trades:number; noTrade:boolean; followedPlan:boolean; riskChecked:boolean; timestamp:string };
type ChainMode = "training" | "licensed";

const MINUTE = 60_000;
function makeScenarioBars(date:string,start:number,drift:number,volatility:number,shockMinute:number,shock:number):Bar[]{
  const openTime=new Date(`${date}T09:30:00-04:00`).getTime();
  return Array.from({length:390},(_,i)=>{
    const shockMove=i>=shockMinute?shock*(1-Math.exp(-(i-shockMinute)/55)):0;
    const base=start+i*drift+Math.sin(i/17)*volatility+Math.sin(i/5.8)*volatility*.28+shockMove;
    const open=base+Math.sin(i*1.23)*volatility*.11,close=base+Math.sin(i*1.91+1)*volatility*.15;
    const wick=.45+volatility*.08+(i%7)*.11;
    return {time:openTime+i*MINUTE,open,close,high:Math.max(open,close)+wick,low:Math.min(open,close)-wick*.86,volume:720+Math.round(Math.abs(Math.sin(i/9))*1400+(i<35?1700-i*25:0)+Math.abs(shockMove)*28)};
  });
}

const scenarioCatalog=[
  {id:1,code:"01",center:5640,title:"开盘结构",focus:"辨认开盘区间、VWAP 与假突破",difficulty:"入门",bars:makeScenarioBars("2024-07-15",5638,.018,4.8,235,-4)},
  {id:2,code:"02",center:5190,title:"趋势与回踩",focus:"等待确认，不在扩张末端追价",difficulty:"基础",bars:makeScenarioBars("2024-08-05",5190,.075,6.4,120,10)},
  {id:3,code:"03",center:5780,title:"高波动日",focus:"在 Gamma 加速环境中控制仓位",difficulty:"进阶",bars:makeScenarioBars("2024-11-06",5782,.032,8.1,175,-18)},
];

function aggregateBars(source: Bar[], frame: number) {
  const result: Bar[] = [];
  for (let i = 0; i < source.length; i += frame) {
    const group = source.slice(i, i + frame);
    if (!group.length) break;
    result.push({ time: group[0].time, open: group[0].open, close: group[group.length - 1].close, high: Math.max(...group.map(b => b.high)), low: Math.min(...group.map(b => b.low)), volume: group.reduce((n, b) => n + b.volume, 0) });
  }
  return result;
}

const lessons = [
  { id: 1, unit: "01", title: "期权语言", subtitle: "权利、义务与合约乘数", status: "完成", duration: "18 分钟", intro: "先把一张期权合约拆开，理解你究竟买了什么。", sections: [{ h: "期权不是股票", p: "买入股票得到资产本身；买入期权得到的是在到期日前按约定价格交易标的资产的权利。买方支付权利金，卖方收取权利金并承担履约义务。" }, { h: "一张合约代表什么", p: "美股标准股票期权通常对应 100 股。报价 $2.40 意味着一张合约成本通常是 $240，而不是 $2.40。SPX 属于现金结算指数期权，结算方式不同。" }, { h: "先看最坏结果", p: "买方最大亏损通常是已付权利金；裸卖方风险可能非常大。每次讨论收益前，先写出最大亏损、盈亏平衡点和到期时间。" }], question: "某 Call 报价 $3.20，标准乘数为 100。买入 1 张至少需要多少权利金？", choices: ["$3.20", "$32", "$320", "$3,200"], answer: 2 },
  { id: 2, unit: "02", title: "价格怎么动", subtitle: "内在价值、时间价值与波动率", status: "完成", duration: "24 分钟", intro: "方向看对仍可能亏损，因为期权价格不只由方向决定。", sections: [{ h: "期权价格的两层", p: "权利金可拆成内在价值和时间价值。价内程度决定内在价值，剩余时间、隐含波动率和利率共同影响时间价值。" }, { h: "Theta：时间不是免费的", p: "其他条件不变时，期权会随到期临近损失时间价值。0DTE 的衰减尤其快，临近收盘时更明显。" }, { h: "Vega：市场在给波动定价", p: "隐含波动率上升通常抬高买方权利金，回落则压低权利金。因此财报前后或重大事件日，不能只判断方向。" }], question: "标的上涨，但你买的 Call 仍亏损，最合理的可能原因是？", choices: ["股票上涨一定赚钱", "隐波回落与时间衰减超过 Delta 收益", "合约乘数变小", "行权价自动变化"], answer: 1 },
  { id: 3, unit: "03", title: "单腿策略", subtitle: "Long Call / Put 与风险边界", status: "进行中", duration: "22 分钟", intro: "用最简单的结构学会表达方向，同时尊重时间和波动率。", sections: [{ h: "什么时候买 Call", p: "你不仅需要看涨，还需要预期上涨发生得足够快、幅度足够大。若隐波很高，方向判断正确也可能被波动率回落抵消。" }, { h: "Delta 不是胜率", p: "Delta 描述标的价格小幅变化时期权价格的敏感度，也常被粗略当作到期价内概率参考，但它不是保证，更不是策略胜率。" }, { h: "入场前的三句话", p: "写清方向证据、判断失效的位置和离场条件。若无法回答其中任何一项，就还没有形成可执行交易。" }], question: "0DTE 买入 Call 前，哪个问题最重要？", choices: ["它昨天涨了多少", "最大收益是否无限", "观点何时失效、最多亏多少", "社区里多少人看多"], answer: 2 },
  { id: 4, unit: "04", title: "垂直价差", subtitle: "方向、成本与收益上限", status: "待解锁", duration: "28 分钟", intro: "用一买一卖降低成本，让风险和目标都变得清楚。", sections: [{ h: "结构", p: "看涨借记价差通常买入较低行权价 Call，同时卖出相同到期日的较高行权价 Call。净支出降低，但最大收益也被封顶。" }, { h: "为什么适合高隐波", p: "卖出的期权能部分抵消买入期权较高的波动率成本，也能减轻部分 Theta 压力。" }, { h: "最大风险", p: "最大亏损通常是净权利金；最大收益通常是行权价差减去净权利金，再乘合约乘数。" }], question: "5 点宽价差净支出 $1.80，单张最大理论收益是多少？", choices: ["$180", "$320", "$500", "无限"], answer: 1 },
  { id: 5, unit: "05", title: "蝶式与鹰式", subtitle: "用结构表达区间观点", status: "待解锁", duration: "31 分钟", intro: "当你的观点不是单纯涨跌，而是价格可能落在某个区域。", sections: [{ h: "蝶式的核心", p: "蝶式由三个行权价构成，中间行权价通常卖出两张。它以有限风险换取价格到期靠近中间行权价时的收益。" }, { h: "铁鹰式", p: "铁鹰式由看跌信用价差与看涨信用价差组成，适合预期价格维持区间、隐波可能下降的情景。" }, { h: "0DTE 的针尖风险", p: "临近到期 Gamma 很高，价格轻微移动就可能大幅改变盈亏。区间策略并不等于低风险。" }], question: "哪种观点更适合考虑铁鹰式？", choices: ["预期单边暴涨", "预期单边暴跌", "预期维持区间且隐波偏高", "完全不知道方向"], answer: 2 },
  { id: 6, unit: "06", title: "0DTE 实战", subtitle: "时间衰减、流动性与纪律", status: "待解锁", duration: "35 分钟", intro: "把图表结构、期权链和仓位风险放进同一个决策流程。", sections: [{ h: "先判断环境", p: "开盘区间、VWAP、前日高低点和更高周期结构，比单根 K 线更重要。先分辨趋势日、区间日还是事件驱动日。" }, { h: "流动性就是成本", p: "价差过宽会让入场和离场都付出额外成本。比较 Bid、Ask、成交量与持仓量，不要只看理论中间价。" }, { h: "训练的目标", p: "目标不是每天交易，而是稳定执行流程。没有优势时不交易，也是一种正确决策。" }], question: "当期权买卖价差很宽时，最合理的做法是？", choices: ["直接市价追单", "增加仓位摊薄成本", "使用限价并评估是否放弃交易", "忽略流动性"], answer: 2 },
];

const normalCdf = (x: number) => { const t = 1 / (1 + .2316419 * Math.abs(x)), d = .3989423 * Math.exp(-x * x / 2), p = 1 - d * t * (.3193815 + t * (-.3565638 + t * (1.781478 + t * (-1.821256 + t * 1.330274)))); return x >= 0 ? p : 1 - p; };
const normalPdf = (x: number) => Math.exp(-x * x / 2) / Math.sqrt(2 * Math.PI);
function optionQuote(strike: number, spot: number, minute: number) {
  const remaining = Math.max(0, 390 - minute), r = .045, q = .013;
  const t = Math.max(1 / (365 * 24 * 60), remaining / (365 * 24 * 60));
  const iv = .145 + Math.max(0, (spot - strike) / spot) * .85 + Math.abs(strike - spot) / spot * .18 + Math.max(0, 150 - minute) / 5000;
  const root = Math.sqrt(t), d1 = (Math.log(spot / strike) + (r - q + iv * iv / 2) * t) / (iv * root), d2 = d1 - iv * root;
  const discQ = Math.exp(-q * t), discR = Math.exp(-r * t);
  const callModel = Math.max(0, spot * discQ * normalCdf(d1) - strike * discR * normalCdf(d2));
  const putModel = Math.max(0, strike * discR * normalCdf(-d2) - spot * discQ * normalCdf(-d1));
  const call = remaining === 0 ? Math.max(0, spot - strike) : Math.max(.05, callModel);
  const put = remaining === 0 ? Math.max(0, strike - spot) : Math.max(.05, putModel);
  const callSpread = Math.max(.1, Math.min(1.5, call * .045 + .08));
  const putSpread = Math.max(.1, Math.min(1.5, put * .045 + .08));
  const gamma = discQ * normalPdf(d1) / (spot * iv * root);
  const vega = spot * discQ * normalPdf(d1) * root / 100;
  const theta = (-(spot * discQ * normalPdf(d1) * iv) / (2 * root) - r * strike * discR * normalCdf(d2) + q * spot * discQ * normalCdf(d1)) / 365;
  const distance = Math.abs(strike - spot), activity = Math.max(0, 1 - distance / 75);
  return {
    strike, delta: discQ * normalCdf(d1), putDelta: -discQ * normalCdf(-d1), gamma, theta, vega, iv,
    bid: Math.max(0, call - callSpread / 2), ask: call + callSpread / 2,
    putBid: Math.max(0, put - putSpread / 2), putAsk: put + putSpread / 2,
    volume: Math.round(280 + activity * 4200 + Math.abs(Math.sin(strike)) * 900),
    openInterest: Math.round(600 + activity * 7600 + Math.abs(Math.cos(strike / 3)) * 1700),
  };
}

function formatTime(ms: number) { return new Intl.DateTimeFormat("zh-CN", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "America/New_York" }).format(ms); }

function TradingChart({ sourceBars, frame, setFrame, replayMinute, tool, setTool, onAction }: { sourceBars:Bar[];frame: number; setFrame: (n: number) => void; replayMinute: number; tool: Tool; setTool: (t: Tool) => void; onAction: (text: string) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  const [drawings, setDrawings] = useState<Drawing[]>([]);
  const [draft, setDraft] = useState<Drawing | null>(null);
  const [cross, setCross] = useState<{ x: number; y: number } | null>(null);
  const [zoom, setZoom] = useState(1);
  const [showMA, setShowMA] = useState(true);
  const [showVWAP, setShowVWAP] = useState(true);
  const bars = useMemo(() => aggregateBars(sourceBars.slice(0, replayMinute + 1), frame), [sourceBars,frame,replayMinute]);
  const visibleCount = Math.max(24, Math.round((frame === 1 ? 95 : frame === 5 ? 72 : 48) / zoom));
  const visible = bars.slice(-visibleCount);

  const render = useCallback(() => {
    const canvas = canvasRef.current, wrap = wrapRef.current;
    if (!canvas || !wrap || !visible.length) return;
    const dpr = window.devicePixelRatio || 1, rect = wrap.getBoundingClientRect();
    canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; canvas.style.width = `${rect.width}px`; canvas.style.height = `${rect.height}px`;
    const ctx = canvas.getContext("2d")!; ctx.scale(dpr, dpr);
    const W = rect.width, H = rect.height, left = 56, right = 66, top = 27, volumeH = 62, bottom = 26, chartBottom = H - bottom - volumeH, plotW = W - left - right;
    const hi = Math.max(...visible.map(b => b.high)), lo = Math.min(...visible.map(b => b.low)), pad = Math.max(2, (hi - lo) * .1), maxP = hi + pad, minP = lo - pad;
    const xAt = (i: number) => left + (i + .5) * (plotW / visible.length), yAt = (p: number) => top + (maxP - p) / (maxP - minP) * (chartBottom - top);
    ctx.fillStyle = "#fbfcfa"; ctx.fillRect(0, 0, W, H);
    ctx.strokeStyle = "#e7ebe7"; ctx.lineWidth = 1;
    for (let i = 0; i <= 5; i++) { const y = top + (chartBottom - top) * i / 5; ctx.beginPath(); ctx.moveTo(left, y); ctx.lineTo(W - right, y); ctx.stroke(); const p = maxP - (maxP - minP) * i / 5; ctx.fillStyle = "#75807b"; ctx.font = "10px ui-monospace"; ctx.fillText(p.toFixed(1), W - right + 8, y + 3); }
    for (let i = 0; i <= 6; i++) { const x = left + plotW * i / 6; ctx.beginPath(); ctx.moveTo(x, top); ctx.lineTo(x, H - bottom); ctx.stroke(); }
    if (showVWAP) { let cumPV = 0, cumV = 0; ctx.strokeStyle = "#c38b2d"; ctx.lineWidth = 1.3; ctx.beginPath(); visible.forEach((b, i) => { cumPV += ((b.high + b.low + b.close) / 3) * b.volume; cumV += b.volume; const x = xAt(i), y = yAt(cumPV / cumV); i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); }
    if (showMA && visible.length > 5) { ctx.strokeStyle = "#4b6fd8"; ctx.lineWidth = 1.3; ctx.beginPath(); visible.forEach((b, i) => { if (i < 4) return; const ma = visible.slice(i - 4, i + 1).reduce((n, z) => n + z.close, 0) / 5, x = xAt(i), y = yAt(ma); i === 4 ? ctx.moveTo(x, y) : ctx.lineTo(x, y); }); ctx.stroke(); }
    const slot = plotW / visible.length, bodyW = Math.max(3, Math.min(11, slot * .64));
    visible.forEach((b, i) => { const x = xAt(i), up = b.close >= b.open, color = up ? "#1d9a73" : "#d75d58"; ctx.strokeStyle = color; ctx.fillStyle = color; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(x + .5, yAt(b.high)); ctx.lineTo(x + .5, yAt(b.low)); ctx.stroke(); const y1 = yAt(b.open), y2 = yAt(b.close), bodyY = Math.min(y1, y2), bodyH = Math.max(1.5, Math.abs(y1 - y2)); ctx.fillRect(x - bodyW / 2, bodyY, bodyW, bodyH); });
    const maxV = Math.max(...visible.map(b => b.volume)); visible.forEach((b, i) => { const vh = b.volume / maxV * (volumeH - 13); ctx.fillStyle = b.close >= b.open ? "#1d9a7355" : "#d75d5855"; ctx.fillRect(xAt(i) - bodyW / 2, H - bottom - vh, bodyW, vh); });
    ctx.fillStyle = "#75807b"; ctx.font = "10px ui-monospace"; [0, .25, .5, .75, 1].forEach(n => { const idx = Math.min(visible.length - 1, Math.floor((visible.length - 1) * n)); ctx.fillText(formatTime(visible[idx].time), xAt(idx) - 14, H - 8); });
    const last = visible[visible.length - 1]; ctx.fillStyle = last.close >= last.open ? "#147d5d" : "#bb4e4a"; const lastY = yAt(last.close); ctx.fillRect(W - right, lastY - 9, right, 18); ctx.fillStyle = "white"; ctx.font = "10px ui-monospace"; ctx.fillText(last.close.toFixed(2), W - right + 7, lastY + 3);
    const allDrawings = draft ? [...drawings, draft] : drawings; ctx.lineWidth = 1.8; ctx.strokeStyle = "#c18425"; ctx.setLineDash([]); allDrawings.forEach(d => { ctx.beginPath(); if (d.type === "trend") { ctx.moveTo(d.x1, d.y1); ctx.lineTo(d.x2, d.y2); } else if (d.type === "horizontal") { ctx.moveTo(left, d.y1); ctx.lineTo(W - right, d.y1); } else ctx.rect(Math.min(d.x1, d.x2), Math.min(d.y1, d.y2), Math.abs(d.x2 - d.x1), Math.abs(d.y2 - d.y1)); ctx.stroke(); });
    if (cross && tool === "cursor") { ctx.strokeStyle = "#5d696488"; ctx.setLineDash([4, 4]); ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(left, cross.y); ctx.lineTo(W - right, cross.y); ctx.moveTo(cross.x, top); ctx.lineTo(cross.x, H - bottom); ctx.stroke(); ctx.setLineDash([]); const index = Math.max(0, Math.min(visible.length - 1, Math.floor((cross.x - left) / slot))); const b = visible[index]; if (b) { ctx.fillStyle = "#18201eee"; ctx.fillRect(Math.max(left, Math.min(cross.x + 9, W - 220)), 8, 202, 19); ctx.fillStyle = "white"; ctx.font = "10px ui-monospace"; ctx.fillText(`O ${b.open.toFixed(1)}  H ${b.high.toFixed(1)}  L ${b.low.toFixed(1)}  C ${b.close.toFixed(1)}`, Math.max(left + 6, Math.min(cross.x + 15, W - 214)), 21); } }
  }, [visible, drawings, draft, cross, tool, zoom, showMA, showVWAP]);

  useEffect(() => { render(); const observer = new ResizeObserver(render); if (wrapRef.current) observer.observe(wrapRef.current); return () => observer.disconnect(); }, [render]);
  const point = (e: React.PointerEvent<HTMLCanvasElement>) => { const r = e.currentTarget.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top }; };
  const onDown = (e: React.PointerEvent<HTMLCanvasElement>) => { const p = point(e); if (tool === "erase") { setDrawings(ds => ds.slice(0, -1)); return; } if (tool !== "cursor") { e.currentTarget.setPointerCapture(e.pointerId); setDraft({ type: tool, x1: p.x, y1: p.y, x2: p.x, y2: p.y } as Drawing); } };
  const onMove = (e: React.PointerEvent<HTMLCanvasElement>) => { const p = point(e); setCross(p); if (draft) setDraft({ ...draft, x2: p.x, y2: p.y }); };
  const onUp = () => { if (draft) { setDrawings(ds => [...ds, draft]); onAction(draft.type === "trend" ? "绘制趋势线" : draft.type === "horizontal" ? "标记水平关键位" : "标记价格区间"); setDraft(null); setTool("cursor"); } };
  const last = visible[visible.length - 1];
  return <div className="pro-chart-shell">
    <div className="chart-commandbar">
      <div className="symbol-block"><b>SPX</b><span>S&P 500 INDEX · CBOE</span></div><div className="ohlc"><b>{last?.close.toFixed(2)}</b><span>O {last?.open.toFixed(2)}</span><span>H {last?.high.toFixed(2)}</span><span>L {last?.low.toFixed(2)}</span><span className={last?.close >= last?.open ? "positive" : "negative"}>C {last?.close.toFixed(2)}</span></div>
      <div className="frame-switch" aria-label="K线周期">{[1, 5, 15].map(n => <button key={n} className={frame === n ? "selected" : ""} onClick={() => setFrame(n)}>{n}m</button>)}</div>
      <button className={showMA ? "indicator-on" : ""} onClick={() => setShowMA(v => !v)}>MA</button><button className={showVWAP ? "indicator-on" : ""} onClick={() => setShowVWAP(v => !v)}>VWAP</button><span className="sample-badge">历史样本</span>
    </div>
    <div className="chart-stage"><div className="draw-toolbar" aria-label="画线工具"><button title="十字光标" className={tool === "cursor" ? "active" : ""} onClick={() => setTool("cursor")}>⌖</button><button title="趋势线" className={tool === "trend" ? "active" : ""} onClick={() => setTool("trend")}>╱</button><button title="水平线" className={tool === "horizontal" ? "active" : ""} onClick={() => setTool("horizontal")}>—</button><button title="矩形" className={tool === "rect" ? "active" : ""} onClick={() => setTool("rect")}>□</button><button title="撤销上一条" onClick={() => setDrawings(ds => ds.slice(0, -1))}>↶</button><button title="清除全部" onClick={() => setDrawings([])}>⌫</button></div><div className="canvas-wrap" ref={wrapRef}><canvas ref={canvasRef} onPointerDown={onDown} onPointerMove={onMove} onPointerLeave={() => setCross(null)} onPointerUp={onUp} /><div className="chart-key"><span className="ma-key">MA5</span><span className="vwap-key">VWAP</span></div><div className="zoom-controls"><button onClick={() => setZoom(z => Math.min(2.3, z + .25))}>＋</button><button onClick={() => setZoom(z => Math.max(.65, z - .25))}>－</button></div></div></div>
  </div>;
}

export default function Home() {
  const [view, setView] = useState<"sim" | "learn" | "quiz" | "report">("sim");
  const [frame, setFrame] = useState(5), [replayMinute, setReplayMinute] = useState(0), [speed, setSpeed] = useState(4), [playing, setPlaying] = useState(false),[scenarioId,setScenarioId]=useState(1);
  const [tool, setTool] = useState<Tool>("cursor"), [selected, setSelected] = useState(5640), [positions, setPositions] = useState<Position[]>([]);
  const [spreadPositions, setSpreadPositions] = useState<SpreadPosition[]>([]), [pendingOrders, setPendingOrders] = useState<PendingOrder[]>([]);
  const [initialCash, setInitialCash] = useState(25000), [cash, setCash] = useState(25000), [realized, setRealized] = useState(0), [maxRiskPct, setMaxRiskPct] = useState(3), [maxDailyLossPct, setMaxDailyLossPct] = useState(4), [consecutiveLosses,setConsecutiveLosses]=useState(0), [accountOpen, setAccountOpen] = useState(false), [draftCash, setDraftCash] = useState("25000");
  const [lessonId, setLessonId] = useState<number | null>(null), [lessonSection, setLessonSection] = useState(0), [lessonChoice, setLessonChoice] = useState<number | null>(null), [completed, setCompleted] = useState<number[]>([]);
  const [review, setReview] = useState(false), [savedNote, setSavedNote] = useState(false), [builderOpen, setBuilderOpen] = useState(false), [orderOpen, setOrderOpen] = useState(false), [orderKind, setOrderKind] = useState<"call"|"spread">("call"), [orderLimit, setOrderLimit] = useState(""), [orderMessage, setOrderMessage] = useState(""), [quizAnswer, setQuizAnswer] = useState<string | null>(null);
  const [events, setEvents] = useState<TradeEvent[]>([]), [noTrade, setNoTrade] = useState(false);
  const [planText,setPlanText]=useState(""),[orderStop,setOrderStop]=useState("35"),[orderTarget,setOrderTarget]=useState("60"),[orderExit,setOrderExit]=useState("330"),[history,setHistory]=useState<TrainingRecord[]>([]);
  const [sessionClosed,setSessionClosed]=useState(false),[chainMode,setChainMode]=useState<ChainMode>("training"),[reviewMessage,setReviewMessage]=useState("");
  const activeScenario=scenarioCatalog.find(s=>s.id===scenarioId)??scenarioCatalog[0],minuteBars=activeScenario.bars;
  useEffect(() => { const saved = Number(localStorage.getItem("options-lab-balance")); if (saved >= 1000) { setInitialCash(saved); setCash(saved); setDraftCash(String(saved)); } try{setHistory(JSON.parse(localStorage.getItem("options-lab-history")||"[]"));setCompleted(JSON.parse(localStorage.getItem("options-lab-progress")||"[]"));}catch{} }, []);
  useEffect(() => { if (!playing || sessionClosed) return; const t = window.setInterval(() => setReplayMinute(v => { if(v>=389){setPlaying(false);return 389;} return v+1;}), Math.max(35, 700 / speed)); return () => clearInterval(t); }, [playing, speed, sessionClosed]);
  const price = minuteBars[replayMinute].close;
  const strikes=useMemo(()=>Array.from({length:21},(_,i)=>activeScenario.center-50+i*5),[activeScenario]);
  const chain = useMemo(() => strikes.map(s => optionQuote(s, price, replayMinute)), [strikes,price,replayMinute]);
  const row = chain.find(r => r.strike === selected)!;
  const log = (kind: TradeEvent["kind"], text: string) => setEvents(xs => [...xs, { id: Date.now() + xs.length, minute: replayMinute, kind, text }]);
  const quoteFor = (strike: number) => optionQuote(strike, price, replayMinute);
  const shortRow = quoteFor(selected + 10), spreadOpenDebit = Math.max(.01, row.ask - shortRow.bid), spreadCloseCredit = Math.max(.01, row.bid - shortRow.ask);
  const singleMarketValue = positions.reduce((sum, p) => sum + quoteFor(p.strike).bid * 100 * p.qty, 0);
  const spreadMarketValue = spreadPositions.reduce((sum, p) => sum + Math.max(.01, quoteFor(p.longStrike).bid - quoteFor(p.shortStrike).ask) * 100 * p.qty, 0);
  const marketValue = singleMarketValue + spreadMarketValue;
  const openCost = positions.reduce((sum, p) => sum + p.entry * 100 * p.qty, 0) + spreadPositions.reduce((sum,p)=>sum+p.entryDebit*100*p.qty,0);
  const unrealized = marketValue - openCost;
  const netLiq = cash + marketValue;
  const reservedBuyingPower = pendingOrders.reduce((sum,o)=>sum+o.limit*100*o.qty,0);
  const availableCash = Math.max(0,cash-reservedBuyingPower);
  const aggregateRisk = openCost + reservedBuyingPower;
  const riskDollars = row.ask * 100, riskPct = riskDollars / initialCash * 100, riskOkay = riskPct <= maxRiskPct;
  const dailyLossLimit=initialCash*maxDailyLossPct/100, equityDrawdown=Math.min(0,netLiq-initialCash), tradingLocked=equityDrawdown<=-dailyLossLimit||consecutiveLosses>=3||sessionClosed;
  const hasDecision=events.some(e=>e.kind==="trade"||e.kind==="discipline")||positions.length>0||spreadPositions.length>0||pendingOrders.length>0;
  const resetSession=(minute=0)=>{setPlaying(false);setReplayMinute(minute);setPositions([]);setSpreadPositions([]);setPendingOrders([]);setCash(initialCash);setRealized(0);setConsecutiveLosses(0);setEvents([]);setPlanText("");setSavedNote(false);setNoTrade(false);setSessionClosed(false);setReviewMessage("");};
  const switchScenario=(id:number)=>{if(id>Math.min(3,history.length+1))return;resetSession(0);setScenarioId(id);setSelected(id===2?5190:id===3?5780:5640);};
  const seekReplay=(next:number)=>{if(hasDecision&&next<replayMinute){setReviewMessage("已有交易决策后不能回到过去。请开始新训练，以避免未来数据污染。");return;}setReplayMinute(next);};
  const setAccount = () => { const n = Math.max(1000, Math.min(10_000_000, Number(draftCash) || 25000)); setInitialCash(n); setCash(n); setPositions([]); setSpreadPositions([]); setPendingOrders([]); setRealized(0); setConsecutiveLosses(0); setEvents([]); setPlanText(""); setSavedNote(false); setSessionClosed(false); localStorage.setItem("options-lab-balance", String(n)); setAccountOpen(false); };
  const previewOrder = () => { setOrderKind("call"); setOrderLimit(row.ask.toFixed(2)); setOrderMessage(""); log("risk", `检查 ${selected} Call：最大风险 $${riskDollars.toFixed(0)}（${riskPct.toFixed(1)}%）`); setOrderOpen(true); };
  const previewSpread = () => { const dollars=spreadOpenDebit*100; setOrderKind("spread"); setOrderLimit(spreadOpenDebit.toFixed(2)); setOrderMessage(""); log("risk", `检查 ${selected}/${selected+10} 看涨价差：最大风险 $${dollars.toFixed(0)}（${(dollars/initialCash*100).toFixed(1)}%）`); setBuilderOpen(false); setOrderOpen(true); };
  const submitOrder = () => { const limit=Math.max(.01,Number(orderLimit)||0), dollars=limit*100, pct=dollars/initialCash*100; if(tradingLocked){setOrderMessage(sessionClosed?"本次训练已经结束，请开始新训练。":"交易已被纪律系统暂停：净值回撤达到上限或连续亏损 3 次。");return;} if(!savedNote||planText.trim().length<20){setOrderMessage("请先写出至少 20 字的交易逻辑、失效条件与退出计划。");return;} if(pct>maxRiskPct){setOrderMessage(`风险超限：按限价计算占账户 ${pct.toFixed(1)}%，规则上限为 ${maxRiskPct}%。`);return;} if(availableCash<dollars){setOrderMessage(`可用购买力不足：已有挂单冻结 $${reservedBuyingPower.toFixed(0)}。`);return;} if(aggregateRisk+dollars>initialCash*maxDailyLossPct/100){setOrderMessage(`组合风险超限：持仓与挂单最大风险合计将达到 $${(aggregateRisk+dollars).toFixed(0)}。`);return;} const order:PendingOrder={id:Date.now(),strategy:orderKind,strike:selected,shortStrike:orderKind==="spread"?selected+10:undefined,qty:1,limit,placedMinute:replayMinute,stopLoss:Number(orderStop)||35,takeProfit:Number(orderTarget)||60,exitMinute:Math.max(replayMinute+1,Number(orderExit)||330)}; setPendingOrders(xs=>[...xs,order]); log("trade",`提交${orderKind==="spread"?`${selected}/${selected+10} 看涨价差`:`${selected} Call`}限价单 $${limit.toFixed(2)}，冻结购买力 $${dollars.toFixed(0)}，止损 ${order.stopLoss}% / 止盈 ${order.takeProfit}% / ${formatTime(minuteBars[Math.min(389,order.exitMinute)].time)} 退出`);setOrderOpen(false);};
  const recordOutcome=(pnl:number)=>setConsecutiveLosses(n=>pnl<0?n+1:0);
  const closePosition = (p: Position,reason="主动平仓") => { const q = quoteFor(p.strike), proceeds = q.bid * 100 * p.qty, pnl = (q.bid - p.entry) * 100 * p.qty; setCash(v => v + proceeds); setRealized(v => v + pnl); recordOutcome(pnl); setPositions(xs => xs.filter(x => x !== p)); log("trade", `${reason}：${p.qty} 张 ${p.strike} Call，成交 $${q.bid.toFixed(2)}，盈亏 ${pnl >= 0 ? "+" : ""}$${pnl.toFixed(0)}`); };
  const closeSpread = (p:SpreadPosition,reason="主动平仓") => { const credit=Math.max(.01,quoteFor(p.longStrike).bid-quoteFor(p.shortStrike).ask), proceeds=credit*100*p.qty,pnl=(credit-p.entryDebit)*100*p.qty;setCash(v=>v+proceeds);setRealized(v=>v+pnl);recordOutcome(pnl);setSpreadPositions(xs=>xs.filter(x=>x!==p));log("trade",`${reason}：${p.longStrike}/${p.shortStrike} 看涨价差，组合成交 $${credit.toFixed(2)}，盈亏 ${pnl>=0?"+":""}$${pnl.toFixed(0)}`);};
  const cancelOrder=(id:number)=>{const o=pendingOrders.find(x=>x.id===id);setPendingOrders(xs=>xs.filter(x=>x.id!==id));if(o)log("discipline",`撤销 ${o.strategy==="spread"?"价差":"单腿"}限价单 $${o.limit.toFixed(2)}`);};
  useEffect(()=>{if(!pendingOrders.length)return;const spot=minuteBars[replayMinute].close;setPendingOrders(orders=>{const waiting:PendingOrder[]=[];orders.forEach(o=>{const long=optionQuote(o.strike,spot,replayMinute);if(o.strategy==="call"){if(long.ask<=o.limit){const fill=long.ask;setCash(v=>v-fill*100*o.qty);setPositions(xs=>[...xs,{strike:o.strike,qty:o.qty,entry:fill,openedMinute:replayMinute,stopLoss:o.stopLoss,takeProfit:o.takeProfit,exitMinute:o.exitMinute}]);log("trade",`${o.strike} Call 限价单成交 $${fill.toFixed(2)}`);}else waiting.push(o);}else{const short=optionQuote(o.shortStrike!,spot,replayMinute),debit=Math.max(.01,long.ask-short.bid);if(debit<=o.limit){setCash(v=>v-debit*100*o.qty);setSpreadPositions(xs=>[...xs,{longStrike:o.strike,shortStrike:o.shortStrike!,qty:o.qty,entryDebit:debit,openedMinute:replayMinute,stopLoss:o.stopLoss,takeProfit:o.takeProfit,exitMinute:o.exitMinute}]);log("trade",`${o.strike}/${o.shortStrike} 看涨价差组合成交 $${debit.toFixed(2)}`);}else waiting.push(o);}});return waiting;});},[replayMinute]);
  useEffect(()=>{if(replayMinute>=389)return;positions.forEach(p=>{const mark=quoteFor(p.strike).bid,change=(mark-p.entry)/p.entry*100;if(change<=-p.stopLoss)closePosition(p,"自动止损");else if(change>=p.takeProfit)closePosition(p,"自动止盈");else if(replayMinute>=p.exitMinute)closePosition(p,"时间退出");});spreadPositions.forEach(p=>{const mark=Math.max(.01,quoteFor(p.longStrike).bid-quoteFor(p.shortStrike).ask),change=(mark-p.entryDebit)/p.entryDebit*100;if(change<=-p.stopLoss)closeSpread(p,"自动止损");else if(change>=p.takeProfit)closeSpread(p,"自动止盈");else if(replayMinute>=p.exitMinute)closeSpread(p,"时间退出");});},[replayMinute]);
  useEffect(()=>{if(replayMinute!==389||sessionClosed)return;setPlaying(false);const cancelled=pendingOrders.length;setPendingOrders([]);positions.forEach(p=>closePosition(p,"16:00 收盘强制平仓"));spreadPositions.forEach(p=>closeSpread(p,"16:00 收盘强制平仓"));setSessionClosed(true);log("discipline",`训练日结束：${cancelled?`撤销 ${cancelled} 张未成交订单；`:""}按 16:00 教学估值完成清算。`);},[replayMinute,sessionClosed]);
  const unresolvedRisk=positions.length+spreadPositions.length+pendingOrders.length;
  const openReview=()=>{setReviewMessage(unresolvedRisk?"请先平仓或撤销全部挂单；未解决风险不能生成最终复盘。":"");setReview(true);};
  const finishNoTrade = () => { if(unresolvedRisk){setReviewMessage("已有持仓或挂单时不能选择不交易。");setReview(true);return;} setNoTrade(true); log("discipline", "主动选择不交易：当前没有满足条件的优势"); setReview(true); };
  const analysisEvidence=events.some(e=>e.text.includes("15 分钟"))&&events.some(e=>e.text.includes("绘制")||e.text.includes("关键位")||e.text.includes("区间"));
  const riskEvidence=events.some(e=>e.kind==="risk"), exitEvidence=events.some(e=>e.text.includes("平仓")||e.text.includes("止损")||e.text.includes("止盈")||e.text.includes("时间退出"))||noTrade;
  const reviewScore=(analysisEvidence?25:0)+(savedNote?25:0)+(riskEvidence?20:0)+(exitEvidence?20:0)+((unresolvedRisk===0&&(events.some(e=>e.kind==="trade")||noTrade))?10:0);
  const saveReview=()=>{if(unresolvedRisk){setReviewMessage("仍有未解决风险，不能保存最终复盘。");return;}const rec:TrainingRecord={id:Date.now(),score:reviewScore,pnl:realized,trades:events.filter(e=>e.text.includes("成交")).length,noTrade,followedPlan:savedNote,riskChecked:riskEvidence,timestamp:new Date().toISOString()};const next=[rec,...history].slice(0,30);setHistory(next);localStorage.setItem("options-lab-history",JSON.stringify(next));setReview(false);};
  const avgScore=history.length?Math.round(history.reduce((n,r)=>n+r.score,0)/history.length):0, totalPnl=history.reduce((n,r)=>n+r.pnl,0), disciplineRate=history.length?Math.round(history.filter(r=>r.followedPlan&&r.riskChecked).length/history.length*100):0, noTradeRate=history.length?Math.round(history.filter(r=>r.noTrade).length/history.length*100):0;
  const learningDays=new Set(history.map(r=>new Date(r.timestamp).toLocaleDateString("zh-CN"))).size,level=1+Math.floor(completed.length/2),xp=completed.length*100+history.length*40;
  const lesson = lessonId ? lessons.find(l => l.id === lessonId)! : null;
  const lessonUnlocked=(id:number)=>id===1||completed.includes(id-1)||completed.includes(id);
  const nextLesson=lessons.find(l=>!completed.includes(l.id)&&lessonUnlocked(l.id))??lessons[lessons.length-1];
  const nav = (v: "sim" | "learn" | "quiz" | "report") => { setView(v); setLessonId(null); };
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">Δ</span><span>期权研习社<small>OPTIONS LAB</small></span></div><nav aria-label="主导航"><button className={view === "sim" ? "active" : ""} onClick={() => nav("sim")}><span>⌁</span>历史回放</button><button className={view === "learn" ? "active" : ""} onClick={() => nav("learn")}><span>◫</span>学习路径</button><button className={view === "quiz" ? "active" : ""} onClick={() => nav("quiz")}><span>◇</span>情景训练</button><button className={view === "report" ? "active" : ""} onClick={() => nav("report")}><span>▥</span>训练报告</button></nav><div className="journey"><div className="journey-top"><span>当前等级</span><b>LV. {level}</b></div><strong>{completed.length===0?"期权初学者":completed.length<3?"风险学习者":"策略探索者"}</strong><div className="progress"><i style={{width:`${Math.min(100,xp%1000/10)}%`}} /></div><small>{xp%1000} / 1,000 XP</small></div><div className="sidebar-foot"><span className="avatar">Y</span><div><b>训练账户</b><small>{learningDays===0?"尚未开始学习":`已记录 ${learningDays} 个学习日`}</small></div><button aria-label="账户设置" onClick={() => setAccountOpen(true)}>•••</button></div></aside>
    <section className="workspace"><header className="topbar"><div><span className="eyebrow">{view === "sim" ? "实战训练 · HISTORICAL REPLAY" : view === "learn" ? "系统课程 · LEARNING PATH" : view === "quiz" ? "判断训练 · SCENARIO DRILLS":"能力追踪 · PERFORMANCE REVIEW"}</span><h1>{view === "sim" ? "SPX 0DTE 历史回放" : view === "learn" ? "从零建立期权思维" : view === "quiz" ? "把知识变成临场判断":"你的交易能力报告"}</h1></div><div className="top-actions"><span className="streak">学习日 <b>{learningDays}</b></span><button className="ghost" onClick={() => nav("learn")}>{completed.length?"继续学习":"从第 1 章开始"}</button><button className="account-chip" onClick={() => setAccountOpen(true)}><span>虚拟账户净值</span><b>${netLiq.toLocaleString(undefined,{maximumFractionDigits:0})}</b><i>设置</i></button></div></header>
      {view === "sim" && <><section className="session-strip"><div className="scenario-picker"><span className="live-dot"/><label><small>训练场景</small><select aria-label="选择训练场景" value={scenarioId} onChange={e=>switchScenario(Number(e.target.value))}>{scenarioCatalog.map(s=><option key={s.id} value={s.id} disabled={s.id>Math.min(3,history.length+1)}>场景 {s.code} · {s.title}{s.id>Math.min(3,history.length+1)?"（完成上一场解锁）":""}</option>)}</select></label><em>{activeScenario.difficulty}</em></div><div className="mission"><span>本场目标</span><b>{activeScenario.focus}</b></div><div className="account"><span>账户净值</span><b>${netLiq.toLocaleString(undefined,{maximumFractionDigits:0})}</b><small className={unrealized >= 0 ? "positive" : "negative"}>未实现 {unrealized >= 0 ? "+" : ""}${unrealized.toFixed(0)} · 已实现 {realized >= 0 ? "+" : ""}${realized.toFixed(0)}</small></div></section>{tradingLocked&&<div className="lock-banner"><b>{sessionClosed?"训练日已结束":"纪律熔断已触发"}</b><span>{sessionClosed?"市场已收盘，订单已清算。":consecutiveLosses>=3?"连续亏损达到 3 次":"账户净值回撤达到当日上限"}。请结束并复盘。</span></div>}
        <section className="terminal-grid"><div className="chart-panel panel"><TradingChart sourceBars={minuteBars} frame={frame} setFrame={(n) => { setFrame(n); log("analysis", `查看 ${n} 分钟周期`); }} replayMinute={replayMinute} tool={tool} setTool={setTool} onAction={(text) => log("analysis", text)}/><div className="playback pro-playback"><button className="round new-session" title="清空当前决策并开始新训练" onClick={() => resetSession(0)}>新训练</button><button className="play" disabled={sessionClosed} onClick={() => setPlaying(v => !v)}>{playing ? "Ⅱ" : "▶"}</button><b>{formatTime(minuteBars[replayMinute].time)} ET</b><input aria-label="回放进度；提交决策后不能回退" type="range" min={hasDecision?replayMinute:0} max="389" value={replayMinute} onChange={e => seekReplay(Number(e.target.value))}/><div className="speed">{[1,2,4,8].map(n => <button key={n} className={speed === n ? "selected" : ""} onClick={() => setSpeed(n)}>{n}×</button>)}</div>{sessionClosed&&<span className="market-closed">已收盘</span>}</div>{hasDecision&&<div className="timeline-lock">时间防穿越已开启：有交易决策后只能向前回放。</div>}</div>
          <div className="coach-panel panel"><div className="coach-head"><div className="coach-icon">✦</div><div><b>AI 交易教练</b><span>记录并审查你的实际行为</span></div><i>在线</i></div><div className="coach-body"><span className="coach-time">{formatTime(minuteBars[replayMinute].time)} · 证据 {events.length} 条</span><h3>先建立证据，再提交订单。</h3><p>教练评分来自你的周期切换、画线、交易计划、风险检查和退出纪律。</p><ol><li className={events.some(e=>e.text.includes("15 分钟"))?"done":""}><b>多周期确认</b><span>{events.some(e=>e.text.includes("15 分钟"))?"已查看 15 分钟结构":"尚未查看 15 分钟结构"}</span></li><li className={savedNote?"done":""}><b>交易计划</b><span>{savedNote?"判断与失效条件已记录":"至少填写 20 个字"}</span></li><li className={events.some(e=>e.kind==="risk")?"done":""}><b>风险预算</b><span>单笔 {maxRiskPct}% · 当日亏损 {maxDailyLossPct}%</span></li></ol><div className="hint"><span>提醒</span>盈利不代表决策正确；系统优先评价过程纪律。</div><textarea aria-label="记录判断" value={planText} placeholder="方向证据、失效位置、预期持有时间和退出理由（至少 20 字）" onChange={e => {setPlanText(e.target.value);setSavedNote(false);}}/><button className="outline" disabled={planText.trim().length<20} onClick={() => { setSavedNote(true); log("analysis","保存完整交易计划与失效条件"); }}>{savedNote ? "✓ 计划已锁定" : planText.trim().length<20?`还需 ${20-planText.trim().length} 字`:"锁定交易计划"}</button><div className="event-mini">{events.slice(-3).reverse().map(e=><span key={e.id}><b>{formatTime(minuteBars[e.minute].time)}</b>{e.text}</span>)}</div></div></div></section>
        <section className="chain-panel panel">
          <div className="chain-head"><div><b>SPX 完整期权链</b><span>21 个行权价 · Call / Put 双边 · Greeks 与流动性</span></div><div className="chain-source" role="tablist" aria-label="期权链数据源"><button className={chainMode==="training"?"active":""} onClick={()=>setChainMode("training")}>训练模型</button><button className={chainMode==="licensed"?"active":""} onClick={()=>setChainMode("licensed")}>真实数据</button></div><div className="chain-summary"><span>现价 <b>{price.toFixed(2)}</b></span><span>剩余 <b>{390-replayMinute} 分钟</b></span></div><button className="strategy-button" onClick={() => setBuilderOpen(true)}>策略构建器 <span>→</span></button></div>
          {chainMode==="licensed"?<div className="licensed-gate"><div><span>OPRA LICENSED FEED · 已验证可行</span><h3>可以获取 SPX 历史逐分钟期权数据</h3><p>已确认 Databento OPRA.PILLAR 提供 CBBO-1m、OHLCV-1m、逐笔成交和合约定义；Polygon 也提供美国期权逐分钟聚合文件。下一步是在服务端配置授权密钥，并按日期预生成训练场景缓存。</p></div><ul><li>CBBO-1m：每分钟历史最优买卖价</li><li>OHLCV-1m：每张合约分钟蜡烛与成交量</li><li>Definition：行权价、到期日和合约身份</li></ul><button onClick={()=>setChainMode("training")}>返回训练链</button></div>:<>
          <div className="chain-disclosure"><b>模型链</b><span>价格与 Greeks 为教学估值；Volume/OI 为模拟流动性指标，不代表 2024-07-15 的真实市场。</span></div>
          <div className="chain-scroll"><div className="chain-table rich"><div className="tr th"><span>CALL BID</span><span>ASK</span><span>Δ</span><span>Γ</span><b>STRIKE</b><span>IV</span><span>Θ/DAY</span><span>VEGA</span><span>PUT Δ</span><span>BID</span><span>ASK</span><span>VOL / OI</span></div>{chain.map(r => <button key={r.strike} className={`tr ${selected === r.strike ? "chosen" : ""}`} onClick={() => setSelected(r.strike)}><span>{r.bid.toFixed(2)}</span><span>{r.ask.toFixed(2)}</span><span>{r.delta.toFixed(2)}</span><span>{r.gamma.toFixed(4)}</span><b>{r.strike}</b><span>{(r.iv*100).toFixed(1)}%</span><span>{r.theta.toFixed(2)}</span><span>{r.vega.toFixed(2)}</span><span>{r.putDelta.toFixed(2)}</span><span>{r.putBid.toFixed(2)}</span><span>{r.putAsk.toFixed(2)}</span><span>{r.volume.toLocaleString()} / {r.openInterest.toLocaleString()}</span></button>)}</div></div>
          <div className={`risk-banner ${riskOkay?"safe":"over"}`}><span>{riskOkay?"✓ 单笔风险符合规则":"! 单笔风险超过规则"}</span><b>单腿 ${riskDollars.toFixed(0)} · 组合已占用 ${aggregateRisk.toFixed(0)} · 挂单冻结 ${reservedBuyingPower.toFixed(0)}</b><small>净值回撤 {Math.abs(equityDrawdown).toFixed(0)} / 当日上限 ${dailyLossLimit.toFixed(0)}</small></div>
          <div className="order-bar"><div><span>已选合约</span><b>SPX {selected} Call</b></div><div><span>模型 Bid / Ask</span><b>${row.bid.toFixed(2)} / ${row.ask.toFixed(2)}</b></div><div><span>可用购买力</span><b>${availableCash.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><button className="buy" disabled={sessionClosed} onClick={previewOrder}>单腿订单</button><button className="no-trade" onClick={finishNoTrade}>选择不交易</button><button className="review-btn" onClick={openReview}>结束并复盘</button></div></>}
          {pendingOrders.length>0&&<div className="orders-panel"><div className="positions-title"><b>待成交订单 · 冻结 ${reservedBuyingPower.toFixed(0)}</b><span>回放推进时检查 Ask / 组合 Debit</span></div>{pendingOrders.map(o=><div className="pending-row" key={o.id}><i>等待</i><b>{o.strategy==="spread"?`${o.strike}/${o.shortStrike} 看涨价差`:`${o.strike} Call`}</b><span>买入开仓 · {o.qty} 张</span><span>限价 ${o.limit.toFixed(2)}</span><span>提交于 {formatTime(minuteBars[o.placedMinute].time)}</span><button onClick={()=>cancelOrder(o.id)}>撤单并释放资金</button></div>)}</div>}
          {(positions.length>0||spreadPositions.length>0)&&<div className="positions-panel"><div className="positions-title"><b>当前持仓</b><span>按可成交侧估值，包含买卖价差</span></div>{positions.map(p=>{const q=quoteFor(p.strike), pnl=(q.bid-p.entry)*100*p.qty;return <div className="position-row" key={`c-${p.strike}`}><b>SPX {p.strike} Call</b><span>{p.qty} 张</span><span>成本 ${p.entry.toFixed(2)}</span><span>Bid ${q.bid.toFixed(2)}</span><strong className={pnl>=0?"positive":"negative"}>{pnl>=0?"+":""}${pnl.toFixed(0)}</strong><button onClick={()=>closePosition(p)}>限价平仓</button></div>})}{spreadPositions.map(p=>{const credit=Math.max(.01,quoteFor(p.longStrike).bid-quoteFor(p.shortStrike).ask),pnl=(credit-p.entryDebit)*100*p.qty;return <div className="position-row spread" key={`s-${p.longStrike}`}><b>{p.longStrike}/{p.shortStrike} 看涨价差</b><span>{p.qty} 组</span><span>成本 ${p.entryDebit.toFixed(2)}</span><span>平仓价 ${credit.toFixed(2)}</span><strong className={pnl>=0?"positive":"negative"}>{pnl>=0?"+":""}${pnl.toFixed(0)}</strong><button onClick={()=>closeSpread(p)}>组合平仓</button></div>})}</div>}
        </section></>}
      {view === "learn" && !lesson && <section className="learning-view"><div className="learning-hero"><span className="eyebrow">你的 8 周路线</span><h2>{completed.length===0?"从第一个概念开始。":"先理解风险，再学习收益。"}</h2><p>每一章都包含可阅读教程、关键概念和检查题。通过本章检查后，下一章才会解锁。</p><div className="hero-stats"><div><b>{Math.round(completed.length / lessons.length * 100)}%</b><span>总进度</span></div><div><b>{completed.length}</b><span>完成章节</span></div><div><b>{completed.length===0?"未开始":"顺序"}</b><span>掌握度解锁</span></div></div></div><div className="module-list">{lessons.map(l => {const unlocked=lessonUnlocked(l.id);return <button key={l.id} disabled={!unlocked} className={`${l.id === nextLesson.id ? "current" : ""} ${!unlocked?"locked":""}`} onClick={() => { if(!unlocked)return;setLessonId(l.id); setLessonSection(0); setLessonChoice(null); }}><span className="module-num">{l.unit}</span><div><b>{l.title}</b><small>{l.subtitle} · {l.duration}</small></div><em>{completed.includes(l.id) ? "已完成" : unlocked?"从这里开始":"🔒 完成上一章解锁"}</em><span className="arrow">{unlocked?"→":""}</span></button>})}</div><aside className="next-lesson"><span className="eyebrow">下一课 · {nextLesson.duration}</span><h3>{nextLesson.title}</h3><p>{nextLesson.intro}</p><div className="mini-payoff"><i/><i/><i/><i/><i/><i/></div><button onClick={() => setLessonId(nextLesson.id)}>{completed.length===0?"开始第一课":"继续学习"} →</button></aside></section>}
      {view === "learn" && lesson && <section className="lesson-reader"><button className="back-link" onClick={() => setLessonId(null)}>← 返回学习路径</button><header><span className="eyebrow">第 {lesson.unit} 章 · {lesson.duration}</span><h2>{lesson.title}</h2><p>{lesson.intro}</p></header><div className="lesson-layout"><aside className="lesson-toc">{lesson.sections.map((s, i) => <button key={s.h} className={lessonSection === i ? "active" : ""} onClick={() => setLessonSection(i)}><span>{i + 1}</span>{s.h}</button>)}<button className={lessonSection === lesson.sections.length ? "active" : ""} onClick={() => setLessonSection(lesson.sections.length)}><span>✓</span>本章检查</button></aside><article className="lesson-content">{lessonSection < lesson.sections.length ? <><span className="lesson-count">{lessonSection + 1} / {lesson.sections.length}</span><h3>{lesson.sections[lessonSection].h}</h3><p>{lesson.sections[lessonSection].p}</p><div className="lesson-example"><b>交易前写下来</b><p>{lesson.id === 1 ? "我买的是一项权利，最多损失已付权利金；报价必须乘以合约乘数。" : lesson.id === 3 ? "方向证据：____　失效位置：____　最多亏损：____" : "这个策略的收益来源是：____　它最怕的市场变化是：____"}</p></div><div className="lesson-nav"><button disabled={lessonSection === 0} onClick={() => setLessonSection(v => v - 1)}>上一节</button><button onClick={() => setLessonSection(v => v + 1)}>下一节 →</button></div></> : <><span className="lesson-count">知识检查</span><h3>{lesson.question}</h3><div className="lesson-choices">{lesson.choices.map((c, i) => <button key={c} className={lessonChoice === i ? "picked" : ""} onClick={() => setLessonChoice(i)}><span>{String.fromCharCode(65+i)}</span>{c}</button>)}</div>{lessonChoice !== null && <div className={`lesson-result ${lessonChoice === lesson.answer ? "correct" : "wrong"}`}><b>{lessonChoice === lesson.answer ? "回答正确" : "还差一步"}</b><p>{lessonChoice === lesson.answer ? "你已经抓住了本章的核心风险逻辑。" : "回到本章内容，重新检查合约乘数、成本或最大风险。"}</p></div>}<button className="complete-lesson" disabled={lessonChoice !== lesson.answer} onClick={() => { setCompleted(xs => {const next=xs.includes(lesson.id)?xs:[...xs,lesson.id];localStorage.setItem("options-lab-progress",JSON.stringify(next));return next;}); setLessonId(null); }}>完成本章并返回</button></>}</article><aside className="lesson-notes"><span>本章目标</span><ul><li>能用自己的话解释概念</li><li>能识别适用情景</li><li>先写最大风险再谈收益</li></ul><button onClick={() => nav("sim")}>去历史回放练习 →</button></aside></div></section>}
      {view === "quiz" && <section className="quiz-view"><div className="quiz-card"><div className="quiz-progress"><span>情景 4 / 10</span><i><b/></i><span>难度：进阶</span></div><span className="eyebrow">0DTE · 开盘 45 分钟</span><h2>方向偏多，但你担心午前波动率回落。哪种表达更合理？</h2><p className="scenario">SPX 位于 VWAP 上方，5 分钟结构高低点抬高。IV 高于近 20 日中位数，你愿意承担最多 $500 风险。</p><div className="answers">{[["A","直接买入近平值 Call"],["B","构建看涨垂直价差"],["C","卖出裸 Put"],["D","买入宽跨式"]].map(([k,v]) => <button key={k} className={quizAnswer === k ? "picked" : ""} onClick={() => setQuizAnswer(k)}><b>{k}</b><span>{v}</span></button>)}</div>{quizAnswer && <div className={`feedback ${quizAnswer === "B" ? "correct" : ""}`}><b>{quizAnswer === "B" ? "判断正确" : "再想一步"}</b><p>{quizAnswer === "B" ? "看涨价差保留方向敞口，同时抵消部分较高隐波成本，并把最大亏损限定在净权利金。" : "你需要同时处理方向、隐波回落和最大风险三个条件。"}</p></div>}</div><aside className="concept-card"><span>本题考点</span><h3>策略不是观点，<br/>而是观点的风险容器。</h3><ul><li>方向：偏多</li><li>波动率：可能回落</li><li>风险：必须封顶</li></ul><button onClick={() => { nav("learn"); setLessonId(4); }}>复习垂直价差 →</button></aside></section>}
      {view === "report" && <section className="report-view"><div className="report-hero"><span className="eyebrow">最近 {history.length} 次训练</span><h2>衡量流程质量，而不只看盈亏。</h2><p>报告保存在当前设备。能力结论需要足够样本，不再用推算数字制造虚假的精确感。</p></div><div className="metric-grid"><div><span>平均过程分</span><b>{avgScore || "—"}</b><small>/ 100 · 行为证据</small></div><div><span>累计模拟盈亏</span><b className={totalPnl>=0?"positive":"negative"}>{totalPnl>=0?"+":""}${totalPnl.toFixed(0)}</b><small>教学模型，不等于实盘</small></div><div><span>计划与风控完成率</span><b>{history.length?`${disciplineRate}%`:"—"}</b><small>来自已保存训练</small></div><div><span>样本可信度</span><b>{history.length>=10?"可观察":history.length>=3?"初步":"不足"}</b><small>{history.length} / 10 次最低观察样本</small></div></div><div className="skill-report"><div className="skill-card evidence-card"><h3>证据覆盖，而非能力雷达</h3><p>下列状态只说明训练中是否留下证据，不宣称真实交易能力。</p>{[["计划 + 风控",history.filter(r=>r.followedPlan&&r.riskChecked).length],["完成交易训练",history.filter(r=>r.trades>0).length],["主动不交易",history.filter(r=>r.noTrade).length]].map(([label,count])=><div className="evidence-row" key={String(label)}><span>{label}</span><b>{count} 次</b><em>{history.length?Math.round(Number(count)/history.length*100):0}% 样本覆盖</em></div>)}</div><div className="coach-summary"><span className="eyebrow">教练结论</span><h3>{history.length<3?"证据不足：先完成至少 3 次训练。":history.length<10?"已有初步流程样本，但不足以判断稳定能力。":disciplineRate<70?"优先修复计划与风控的一致性。":"流程证据开始稳定，继续覆盖不同市场环境。"}</h3><ul><li>盈利与正确决策分开评价</li><li>未平仓风险不能进入最终复盘</li><li>至少 10 次不同环境样本后再谈稳定性</li></ul><button onClick={()=>nav("sim")}>开始下一次训练 →</button></div></div><div className="history-table"><div className="history-head"><b>训练历史</b><span>最多保存最近 30 次</span></div>{history.length?history.map(r=><div className="history-row" key={r.id}><time>{new Date(r.timestamp).toLocaleDateString("zh-CN")}</time><b>{r.score} 分</b><span className={r.pnl>=0?"positive":"negative"}>{r.pnl>=0?"+":""}${r.pnl.toFixed(0)}</span><span>{r.noTrade?"主动不交易":`${r.trades} 次成交`}</span><em>{r.followedPlan&&r.riskChecked?"流程合规":"需要复盘"}</em></div>):<div className="empty-report"><b>还没有训练记录</b><span>完成一次历史回放并保存复盘后，这里会生成长期能力报告。</span><button onClick={()=>nav("sim")}>开始训练</button></div>}</div></section>}
    </section>
    {accountOpen && <div className="modal-backdrop" onClick={() => setAccountOpen(false)}><section className="account-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setAccountOpen(false)}>×</button><span className="eyebrow">模拟账户设置</span><h2>资金与风险规则</h2><p>调整会清空当前模拟仓位、盈亏和行为日志。历史训练报告不会被删除。</p><label>初始资金（美元）<input type="number" min="1000" max="10000000" step="1000" value={draftCash} onChange={e => setDraftCash(e.target.value)}/></label><div className="preset-cash">{[10000,25000,100000,1000000].map(n => <button key={n} onClick={() => setDraftCash(String(n))}>${n.toLocaleString()}</button>)}</div><label>单笔最大风险：{maxRiskPct}%<input type="range" min="1" max="10" step="1" value={maxRiskPct} onChange={e=>setMaxRiskPct(Number(e.target.value))}/></label><label>当日最大亏损：{maxDailyLossPct}%<input type="range" min="1" max="10" step="1" value={maxDailyLossPct} onChange={e=>setMaxDailyLossPct(Number(e.target.value))}/></label><small className="risk-help">达到当日亏损上限或连续亏损 3 次后，系统会暂停新订单。</small><button className="submit" onClick={setAccount}>保存并重置账户</button></section></div>}
    {review && <div className="modal-backdrop" onClick={() => setReview(false)}><section className="review-modal evidence-review" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setReview(false)}>×</button><span className="eyebrow">行为证据复盘 · {events.length} 条记录</span><h2>{noTrade?"你选择了不交易；系统只评价是否有证据支持。":"过程分与盈亏分开，不用结果替代决策质量。"}</h2><div className="score-ring"><b>{reviewScore}</b><span>/ 100</span></div>{reviewMessage&&<div className="review-blocker"><b>复盘尚未闭环</b><span>{reviewMessage}</span></div>}<div className="review-grid"><div><span>分析过程 · 25</span><b>{analysisEvidence?"周期与图表证据完整":"证据不完整"}</b><p>{analysisEvidence?"已同时留下高周期确认和图表标记。":"需要同时查看 15 分钟结构并留下有效图表标记。"}</p></div><div><span>交易计划 · 25</span><b>{savedNote?"计划已锁定":"未形成书面计划"}</b><p>{savedNote?"系统记录了交易逻辑、失效条件与自动退出。":"没有明确失效条件时，不应开放订单。"}</p></div><div><span>风险与退出 · 40</span><b>{riskEvidence&&exitEvidence?"形成闭环":"仍缺风险或退出证据"}</b><p>{unresolvedRisk?`尚有 ${unresolvedRisk} 项未解决风险。`:`持仓和挂单已清零；当日风险上限 ${maxDailyLossPct}%。`}</p></div></div><div className="audit-log"><b>本次行为时间线</b>{events.length?events.map(e=><div key={e.id}><time>{formatTime(minuteBars[e.minute].time)}</time><span>{e.text}</span></div>):<p>尚无可评分的行为证据。请完成画线、周期确认和计划记录。</p>}</div><button className="submit" disabled={unresolvedRisk>0} onClick={saveReview}>{unresolvedRisk?"先解决全部持仓与挂单":"保存到训练报告"}</button></section></div>}
    {orderOpen && <div className="modal-backdrop" onClick={() => setOrderOpen(false)}><section className="order-modal managed-order" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOrderOpen(false)}>×</button><span className="eyebrow">模拟订单确认</span><h2>买入开仓 · {orderKind==="spread"?`${selected}/${selected+10} 看涨价差`:`SPX ${selected} Call`}</h2><div className="ticket-grid"><div><span>数量</span><b>1 {orderKind==="spread"?"组":"张"}</b></div><div><span>订单类型</span><b>组合限价单</b></div><div><span>当前可成交价</span><b>${(orderKind==="spread"?spreadOpenDebit:row.ask).toFixed(2)}</b></div><div><span>有效期</span><b>当日</b></div><div><span>最大亏损</span><b>${((Number(orderLimit)||0)*100).toFixed(0)}</b></div><div><span>账户占比</span><b className={(Number(orderLimit)||0)*100/initialCash*100<=maxRiskPct?"positive":"negative"}>{((Number(orderLimit)||0)*100/initialCash*100).toFixed(1)}%</b></div></div><label className="limit-field">买入限价（每份）<input type="number" min="0.01" step="0.05" value={orderLimit} onChange={e=>{setOrderLimit(e.target.value);setOrderMessage("");}}/><small>低于当前可成交价时进入等待队列。</small></label><div className="exit-plan"><label>止损<input type="number" min="5" max="95" value={orderStop} onChange={e=>setOrderStop(e.target.value)}/><span>%</span></label><label>止盈<input type="number" min="5" max="500" value={orderTarget} onChange={e=>setOrderTarget(e.target.value)}/><span>%</span></label><label>最晚退出<select value={orderExit} onChange={e=>setOrderExit(e.target.value)}><option value="270">14:00</option><option value="330">15:00</option><option value="375">15:45</option></select></label></div><p className="model-warning">成交后系统会按可成交侧自动监控止损、止盈和时间退出。教学模型并不保证真实市场可在相同价格成交。</p>{orderMessage&&<div className="order-error">{orderMessage}</div>}<button className="submit" onClick={submitOrder}>确认计划并提交限价单</button></section></div>}
    {builderOpen && <div className="modal-backdrop" onClick={() => setBuilderOpen(false)}><section className="strategy-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setBuilderOpen(false)}>×</button><span className="eyebrow">策略构建器 · 有限风险</span><h2>看涨垂直价差</h2><p>买入 {selected} Call，同时卖出 {selected + 10} Call。两腿作为一张组合订单提交，不模拟裸腿成交风险。</p><div className="legs"><div><b>＋1</b><span>买入 {selected} Call</span><em>Ask ${row.ask.toFixed(2)}</em></div><div><b>－1</b><span>卖出 {selected + 10} Call</span><em>Bid ${shortRow.bid.toFixed(2)}</em></div></div><div className="risk-metrics"><div><span>当前净支出</span><b>${(spreadOpenDebit*100).toFixed(0)}</b></div><div><span>最大收益</span><b>${(1000-spreadOpenDebit*100).toFixed(0)}</b></div><div><span>盈亏平衡</span><b>{(selected+spreadOpenDebit).toFixed(2)}</b></div></div><p className="model-warning">最大亏损为净支出，最大收益为行权价宽度减净支出。实际成交前仍需通过账户风险规则。</p><button className="submit" onClick={previewSpread}>创建组合限价单</button></section></div>}
  </main>;
}
